### ISSUE TITLE
Forward Compatability for Windows GUI

### ISSUE THREAD

**Issue by jlopata21** [samaygarg/fuelcell#5]
I'm using Windows 10.0.19041 and Python 3.9.1150. After installing Python to /AppData/Local, fuelcell using pip, and then the Windows GUI to /Desktop, opening the GUI resulted in two warnings: 1) "The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3." and 2) "fuelcell_gui_v02.py:473: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python." After these warnings appear, the GUI does not open. I rolled matplotlib back from 3.3.3 to 3.2.2 and got the same result. The same warnings appear after uninstalling Python 3.9.1 and installing Python 3.8.7 with fuelcell. Is there a specific version of Python that should be used for the current version of fuelcell?

**Comment by shimpalee** [comment]
I am having the same issue as Joe Lopata (jlopata21). Therefore I cannot evaluate further.

**Comment by samaygarg** [comment]
I am working to resolve this issue. fuelcell should be compatible with any version of Python 3

**Comment by jgostick** [comment]
Great stuff @samaygarg.

**Comment by shimpalee** [comment]
Dear Samay
Please let us know if you have fixed the problem so we can continue testing your code.
Best

**Comment by samaygarg** [comment]
Hi all,

This issue should be resolved in GUI v0.5.2. The standalone GUI files are now located in zip files on the [releases page](https://github.com/samaygarg/fuelcell/releases) for this repository, and the [documentation](https://fuelcell.readthedocs.io/en/latest/gui.html) has been updated to reflect the new installation instructions. Apologies for the delay; recent changes in COVID restrictions made it difficult to get consistent access to a windows 10 machine for a couple weeks.

~Samay
