### ISSUE TITLE
Attribute Errors for 'folder_txtbx_upload' and 'set_expt_type'

### ISSUE THREAD

**Issue by jlopata21** [samaygarg/fuelcell#6]
Using Python 3.8.7 on Windows 10, after updating the GUI to version 0-5-2, the GUI opens, but I encountered the issues below. 

1) While trying to specify an export directory other than the default, GUI throws the following error:

Traceback (most recent call last):
  File "fuelcell_gui.py", line 884, in saveloc_action_data
    self.folder_txtbx_upload.setText(folder)
AttributeError: 'FuelcellUI' object has no attribute 'folder_txtbx_upload'

I noticed that Line 884 contained the first instance of folder_txtbx_upload in fuelcell_gui.py.

2) Trying to process eis_01.xlsx and cv_00.xlsx. After clicking "Process data," GUI throws the following error:

Traceback (most recent call last):
  File "fuelcell_gui.py", line 888, in process_action
    self.datahandler.process_data()
  File "fuelcell_gui.py", line 66, in process_data
    self.load_raw_data()
  File "fuelcell_gui.py", line 60, in load_raw_data
    all_data = fc.load_data(filename=self.files, folder=self.folder, expt_type=self.expt_type)
  File "C:\Users\joelo\AppData\Local\Programs\Python\Python38\lib\site-packages\fuelcell\datums.py", line 63, in load_data
    this_data.set_expt_type(expt_type.lower())
AttributeError: 'NoneType' object has no attribute 'set_expt_type'

**Comment by samaygarg** [comment]
Sorry for this hiccough; we disabled a portion of the error handling to assist with internal testing and debugging and it was never re-enabled. Both issues are now resolved in v0.5.3

**Comment by samaygarg** [comment]
Sorry for this hiccough; we disabled a portion of the error handling to assist with internal testing and debugging and it was never re-enabled. Both issues are now resolved in v0.5.3

**Comment by jgostick** [comment]
So is this issue closed then?  I'd like to see the JOSS submission get moving forward.

**Comment by samaygarg** [comment]
yes this issue is closed
